name: CI

on:
  workflow_dispatch:

  push:
    branches:
      - '**'

jobs:
  Runner:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git source
        uses: actions/checkout@v3
      
      - name: Setup docker
        uses: docker-practice/actions-setup-docker@1.0.9

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm i --force

      - name: Continuous integration
        run: |
          npm run lint
          npm run test
          # docker run -i --entrypoint=bash -v `pwd`:/root/tmp --rm mcr.microsoft.com/playwright:v1.26.0-focal -c "cd /root/tmp && ./test/ci.sh"

      - name: Code coverage
        uses: codecov/codecov-action@v3.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
